Repository laujamie/music-queuer, pull requests merged in 2024-03, with the labels that each got.

#6 Add input link and queue functionality
  src/app/page.tsx
  src/components/LinkInput.tsx
  src/components/VideoPlayer.tsx
Labels: FE

#8 Add visual queue list
  src/app/page.tsx
  src/components/QueueList.tsx
  src/components/VideoPlayer.tsx
Labels: FE

#11 Add backend queue system with rough frontend integration
  convex/_generated/api.d.ts
  convex/_generated/dataModel.d.ts
  convex/lib/auth.ts
  convex/lib/slug.ts
  convex/queues.ts
  convex/schema.ts
  convex/shared.ts
  package.json
  pnpm-lock.yaml
  src/app/[queueCode]/page.tsx
  src/app/page.tsx
  src/components/ConvexClientProvider.tsx
  src/components/LinkInput.tsx
  src/components/VideoPlayer.tsx
  tsconfig.json
Labels: backend

#17 Update UI components
  components.json
  package.json
  pnpm-lock.yaml
  src/app/[queueCode]/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/LinkInput.tsx
  src/components/ModePicker.tsx
  src/components/QueueList.tsx
  src/components/ThemeProvider.tsx
  src/components/VideoPlayer.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/separator.tsx
  src/lib/utils.ts
  tailwind.config.ts
Labels: frontend

#18 Add initial Convex action for YouTube search API
  convex/_generated/api.d.ts
  convex/lib/youtube.ts
  convex/youtube.ts
Labels: backend
